projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      # endpoints: "http://localhost:7777"
        default: "http://localhost:4000"
  prisma:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: prisma.yml
